version: "2"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    command: /usr/app/node_modules/.bin/nodemon -L /src/App.ts
    volumes:
      - ./api/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_ENV=development
    command: yarn start
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    ports:
      - "3000:3000"
