apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: agoraplatform/api:$COMMIT_SHA1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongoURI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: jwtSecret
            - name: SPACES_NAME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: spacesName
            - name: SPACES_REGION
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: spacesRegion
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: spacesKey
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: spacesSecret
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: elasticsearchPassword
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  key: elasticsearchUrl
                  name: api-secrets
