apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: agoraplatform/client:$COMMIT_SHA1
          resources:
            requests:
              cpu: "166m"
              memory: "333Mi"
            limits:
              cpu: "333m"
              memory: "666Mi"
          ports:
            - containerPort: 3000
