apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  accessModes:
    # Can be read/written by a single node
    - ReadWriteOnce
  resources:
    requests:
      # Kubernetes will have to find a storage option that has 2 gigabytes of space
      storage: 1Mi
