apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # Tell Kubernetes to make an Ingress controller based on the Nginx project
    kubernetes.io/ingress.class: nginx
    # Configure how our copy of Nginx behaves
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Removes '/api' from request
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
# Define our nginx routing
spec:
  rules:
    - host: agora.voto
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /graphql/?(.*)
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 8080
    - host: www.agora.voto
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /graphql/?(.*)
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 8080
    # - http:
    #     paths:
    #       - path: /?(.*)
    #         backend:
    #           serviceName: client-cluster-ip-service
    #           servicePort: 3000
    #       - path: /graphql/?(.*)
    #         backend:
    #           serviceName: server-cluster-ip-service
    #           servicePort: 5000
