apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: agoraplatform/api
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: development
            - name: MONGO_URI
              value: mongodb+srv://devin:chaos1@cluster0.hlyry.mongodb.net/development?retryWrites=true&w=majority
            - name: JWT_SECRET
              value: donttellanyoneaboutthissecretplease
            - name: SPACES_NAME
              value: agora-dev
            - name: SPACES_REGION
              value: sfo3
            - name: SPACES_KEY
              value: WSSFOK5LKJ5PP5XIHQEA
            - name: SPACES_SECRET
              value: fFtvsxm4rX7QzX09RXLWchJUXb1Uda3bbnJREKTVVH0
