export default {
  Page: 1,
  PageConnection: 1,
  Paragraph: 1,
  ParagraphEditProposal: 1,
  Question: 1,
  QuestionPageConnection: 1,
  Statement: 1,
  Variable: 1,
  VariableEditProposal: 1,
  VariablePageConnection: 1,
  User: 1,
  UserVerificationRequest: 1,
  File: 1,
};
